systemctl --user import-environment DISPLAY

# Ensure keyrings with seahorse works
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Setup Xresources for term if they exist
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Load nvidia settings if they exist
[[ -f ~/.nvidia-settings-rc ]] && nvidia-settings --load-config-only

# disable blanking and enable dpms features, 5 min timeouts
xset s off
xset s noblank
xset dpms 300 300 300

# set capslock to be control
setxkbmap -option caps:ctrl_modifier

# jp ime
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

# Start i3!
exec i3
