---
- hosts: 127.0.0.1
  connection: local
  vars:
    desktop: "{{ ansible_hostname == 'kanade' }}"
    laptop: "{{ ansible_hostname == 'narumi' }}"
  tasks:
    # Networking
    - name: Create systemd/network directory
      become: true
      file:
        path: /etc/systemd/network
        state: directory
        mode: "0755"

    - name: Fallback DNS configuration
      become: true
      template:
        src: ./templates/systemd/resolved.conf.d/fallback_dns.conf
        dest: /etc/systemd/resolved.conf.d/fallback_dns.conf
        owner: root
        group: root
        mode: "0644"

    - name: Disable resolved multicast
      become: true
      template:
        src: ./templates/systemd/resolved.conf.d/disable_multicast.conf
        dest: /etc/systemd/resolved.conf.d/disable_multicast.conf
        owner: root
        group: root
        mode: "0644"

    - name: Network configuration (dhcp)
      become: true
      template:
        src: ./templates/systemd/network/20-dhcp.network
        dest: /etc/systemd/network/20-dhcp.network
        owner: root
        group: root
        mode: "0644"

    - name: Network configuration (wifi device)
      become: true
      template:
        src: ./templates/etc/iwd/main.conf
        dest: /etc/iwd/main.conf
        owner: root
        group: root
        mode: "0644"

    - name: Use systemd-resolved DNS config stub
      become: true
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link

    - name: Create systemd user directory
      file:
        path: ~/.config/systemd/user
        state: directory

    - name: Geoclue agent unit file
      template:
        src: ./templates/systemd/user/geoclue-agent.service
        dest: ~/.config/systemd/user/geoclue-agent.service

    - name: Configure timesyncd
      become: true
      blockinfile:
        insertafter: "[Time]"
        path: "/etc/systemd/timesyncd.conf"
        mode: "0644"
        block: |
          NTP=au.pool.ntp.org
          FallbackNTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org

    - name: Create liquid cooler unit file
      become: true
      template:
        src: ./templates/systemd/system/liquidctl.service
        dest: /etc/systemd/system/liquidctl.service
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop

    - name: Create OpenRGB unit file
      become: true
      template:
        src: ./templates/systemd/system/openrgb.service
        dest: /etc/systemd/system/openrgb.service
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop

    # Reload to ensure all following starts are using new config
    - name: Reload systemd (system)
      become: true
      systemd:
        daemon_reload: true

    - name: Reload systemd (user)
      systemd:
        daemon_reload: true
        scope: user

    # Start services
    - name: Start & enable systemd-networkd
      become: true
      service:
        name: systemd-networkd
        state: started
        enabled: true

    - name: Start & enable iwd
      become: true
      service:
        name: iwd
        state: started
        enabled: true
      when:
        - laptop

    - name: Start & enable systemd-resolved
      become: true
      service:
        name: systemd-resolved
        state: started
        enabled: true

    - name: Start & enable timesyncd
      become: true
      service:
        name: systemd-timesyncd
        state: started
        enabled: true

    - name: Start & enable geoclue-agent
      service:
        name: geoclue-agent
        state: started
        enabled: true
        scope: user

    - name: Start & enable pipewire-pulse
      service:
        name: pipewire-pulse
        state: started
        enabled: true
        scope: user

    - name: Liquid cooler configuration service
      become: true
      service:
        name: liquidctl
        state: started
        enabled: true
      when:
        - desktop

    - name: OpenRGB configuration service
      become: true
      service:
        name: openrgb
        state: started
        enabled: true
      when:
        - desktop

    # Configure Xorg
    - name: Nvidia display configuration
      become: true
      template:
        src: ./templates/xorg.conf.d/10-nvidia.conf
        dest: /etc/X11/xorg.conf.d/10-nvidia.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop
    - name: Mouse/trackpad configuration
      become: true
      template:
        src: ./templates/xorg.conf.d/20-mouse.conf
        dest: /etc/X11/xorg.conf.d/20-mouse.conf
        owner: root
        group: root
        mode: "0644"

    - name: Keyboard configuration
      become: true
      template:
        src: ./templates/xorg.conf.d/30-keyboard.conf
        dest: /etc/X11/xorg.conf.d/30-keyboard.conf
        owner: root
        group: root
        mode: "0644"

    # Kernel modules
    - name: Blacklist i2c nvidia driver
      become: true
      template:
        src: ./templates/etc/modprobe.d/i2c-nvidia-gpu-blacklist.conf
        dest: /etc/modprobe.d/i2c-nvidia-gpu-blacklist.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop
    - name: Disable fTPM
      become: true
      template:
        src: ./templates/etc/modprobe.d/tpm_crb-blacklist.conf
        dest: /etc/modprobe.d/tpm_crb-blacklist.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop
    - name: Enable V4L2Loopback
      become: true
      template:
        src: ./templates/etc/modprobe.d/v4l2loopback.conf
        dest: /etc/modprobe.d/v4l2loopback.conf
        owner: root
        group: root
        mode: "0644"
    - name: Enable fnmode=2 for hid_apple devices
      become: true
      template:
        src: ./templates/etc/modprobe.d/hid_apple.conf
        dest: /etc/modprobe.d/hid_apple.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop

    # Sysctl config
    - name: Lower swappiness
      become: true
      template:
        src: ./templates/etc/sysctl.d/99-swappiness.conf
        dest: /etc/sysctl.d/99-swappiness.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - desktop
