#!/usr/bin/env bash
# Find processes listening on a TCP port
# Usage: listening 8000
if [ $# -eq 0 ]; then
  sudo lsof -iTCP -sTCP:LISTEN -n -P
elif [ $# -eq 1 ]; then
  sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
else
  echo "Usage: listening [pattern]"
fi
