---
- hosts: 127.0.0.1
  connection: local
  vars:
    desktop: "{{ ansible_hostname == 'kanade' }}"
  tasks:
    # Networking
    - name: Create systemd/network directory
      become: true
      file:
        path: /etc/systemd/network
        state: directory
        mode: '0755'

    - name: Fallback DNS configuration
      become: true
      template:
        src: ./templates/systemd/resolved.conf.d/fallback_dns.conf
        dest: /etc/systemd/resolved.conf.d/fallback_dns.conf
        owner: root
        group: root
        mode: '0644'

    - name: Network configuration
      become: true
      template:
        src: ./templates/systemd/network/20-eth0.network
        dest: /etc/systemd/network/20-eth0.network
        owner: root
        group: root
        mode: '0644'

    - name: Use systemd-resolved DNS config stub
      become: true
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link

    - name: Geoclue agent unit file
      template:
        src: ./templates/systemd/user/geoclue-agent.service
        dest: ~/.config/systemd/user/geoclue-agent.service
      when:
        - desktop

    - name: Configure timesyncd
      become: true
      blockinfile:
        insertafter: "[Time]"
        path: "/etc/systemd/timesyncd.conf"
        mode: "0644"
        block: |
          NTP=au.pool.ntp.org
          FallbackNTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org

    - name: Create liquid cooler unit file
      become: true
      template:
        src: ./templates/systemd/system/liquidcfg.service
        dest: /etc/systemd/system/liquidcfg.service
        owner: root
        group: root
        mode: '0644'
      when:
        - desktop

    # Reload to ensure all following starts are using new config
    - name: Reload systemd (system)
      become: true
      systemd:
        daemon_reload: true

    - name: Reload systemd (user)
      systemd:
        daemon_reload: true
        scope: user

    # Start services
    - name: Start & enable systemd-networkd
      become: true
      service:
        name: systemd-networkd
        state: started
        enabled: true

    - name: Start & enable systemd-resolved
      become: true
      service:
        name: systemd-resolved
        state: started
        enabled: true

    - name: Start & enable timesyncd
      become: true
      service:
        name: systemd-timesyncd
        state: started
        enabled: true

    - name: Start & enable geoclue-agent
      service:
        name: geoclue-agent
        state: started
        enabled: true
        scope: user

    - name: Liquid cooler configuration service
      become: true
      service:
        name: liquidcfg
        state: started
        enabled: true
      when:
        - desktop

    # Configure Xorg
    - name: Nvidia configuration
      become: true
      when:
        - desktop
      template:
        src: ./templates/xorg.conf.d/10-nvidia.conf
        dest: /etc/X11/xorg.conf.d/10-nvidia.conf
        owner: root
        group: root
        mode: '0644'

    - name: Mouse/trackpad configuration
      become: true
      template:
        src: ./templates/xorg.conf.d/20-mouse.conf
        dest: /etc/X11/xorg.conf.d/20-mouse.conf
        owner: root
        group: root
        mode: '0644'

    - name: Keyboard configuration
      become: true
      template:
        src: ./templates/xorg.conf.d/30-keyboard.conf
        dest: /etc/X11/xorg.conf.d/30-keyboard.conf
        owner: root
        group: root
        mode: '0644'
