[aws]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"

[line_break]
disabled = true

[package]
disabled = true
